logging :
  level :
    org :
      thymeleaf : DEBUG


server :
  port : 8081
  context-path : /sample1

authenticationFilter :
  serverName : http://localhost:8081/sample1
  casServerLoginUrl : https://localhost:8443/cas/login


validationFilter :
  casServerUrlPrefix : https://localhost:8443/cas

